version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
  mnemonic: twin castle action employ volume maid butter elevator nose client away garbage
    cup interest helmet transfer banner action party perfect happy toilet sweet   
    luggage
- name: bob
  coins:
  - 10000token
  - 100000000stake
  mnemonic: kangaroo animal piano craft open shine fog solar car bread fee inform seven
    later reason quiz into sun shrimp mind various unfold drastic fun
- name: carol
  coins:
  - 10000token
  - 100000000stake
  mnemonic: devote guess visa weasel boat shed obvious half cloud dream hunt almost faith
    iron drop agree unfold service grunt reduce apple nut cherry style
validators:
- name: alice
  mnemonic: twin castle action employ volume maid butter elevator nose client away garbage
    cup interest helmet transfer banner action party perfect happy toilet sweet   
    luggage
  bonded: 100000000stake
  config:
    consensus:
      timeout_commit: 2s
    log_level: error
genesis:
  app_state:
    twin:
      params:
        authorized_accounts: ["vesta15xhpaax757zz76x8p96ku2gwuyvh4wz0d5h400", "vesta1u89k93p3q7fj4l5u5um3sas2ege9wmt3tk6l64", "vesta1vh9m4j59gwnwxw9vye003hy3sjfh2lp25s000f"]