// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesta/twin/training_state.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TrainingState struct {
	Value                     bool             `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	TwinName                  string           `protobuf:"bytes,2,opt,name=twin_name,json=twinName,proto3" json:"twin_name,omitempty"`
	StartTime                 time.Time        `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	TrainingConfigurationHash string           `protobuf:"bytes,4,opt,name=training_configuration_hash,json=trainingConfigurationHash,proto3" json:"training_configuration_hash,omitempty"`
	ValidationState           *ValidationState `protobuf:"bytes,5,opt,name=validation_state,json=validationState,proto3" json:"validation_state,omitempty"`
}

func (m *TrainingState) Reset()         { *m = TrainingState{} }
func (m *TrainingState) String() string { return proto.CompactTextString(m) }
func (*TrainingState) ProtoMessage()    {}
func (*TrainingState) Descriptor() ([]byte, []int) {
	return fileDescriptor_672fc39fef593be7, []int{0}
}
func (m *TrainingState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainingState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainingState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainingState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingState.Merge(m, src)
}
func (m *TrainingState) XXX_Size() int {
	return m.Size()
}
func (m *TrainingState) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingState.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingState proto.InternalMessageInfo

func (m *TrainingState) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *TrainingState) GetTwinName() string {
	if m != nil {
		return m.TwinName
	}
	return ""
}

func (m *TrainingState) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *TrainingState) GetTrainingConfigurationHash() string {
	if m != nil {
		return m.TrainingConfigurationHash
	}
	return ""
}

func (m *TrainingState) GetValidationState() *ValidationState {
	if m != nil {
		return m.ValidationState
	}
	return nil
}

type ValidationState struct {
	Value                       bool              `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	StartTime                   time.Time         `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time"`
	MapValidatorsBestresulthash map[string]string `protobuf:"bytes,3,rep,name=map_validators_bestresulthash,json=mapValidatorsBestresulthash,proto3" json:"map_validators_bestresulthash,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ValidationState) Reset()         { *m = ValidationState{} }
func (m *ValidationState) String() string { return proto.CompactTextString(m) }
func (*ValidationState) ProtoMessage()    {}
func (*ValidationState) Descriptor() ([]byte, []int) {
	return fileDescriptor_672fc39fef593be7, []int{1}
}
func (m *ValidationState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidationState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidationState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidationState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidationState.Merge(m, src)
}
func (m *ValidationState) XXX_Size() int {
	return m.Size()
}
func (m *ValidationState) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidationState.DiscardUnknown(m)
}

var xxx_messageInfo_ValidationState proto.InternalMessageInfo

func (m *ValidationState) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *ValidationState) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *ValidationState) GetMapValidatorsBestresulthash() map[string]string {
	if m != nil {
		return m.MapValidatorsBestresulthash
	}
	return nil
}

func init() {
	proto.RegisterType((*TrainingState)(nil), "vesta.twin.TrainingState")
	proto.RegisterType((*ValidationState)(nil), "vesta.twin.ValidationState")
	proto.RegisterMapType((map[string]string)(nil), "vesta.twin.ValidationState.MapValidatorsBestresulthashEntry")
}

func init() { proto.RegisterFile("vesta/twin/training_state.proto", fileDescriptor_672fc39fef593be7) }

var fileDescriptor_672fc39fef593be7 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x3d, 0xaf, 0xd3, 0x30,
	0x14, 0x8d, 0x13, 0x1e, 0x6a, 0xfc, 0x84, 0xde, 0x93, 0xf5, 0x86, 0x90, 0x88, 0x24, 0x7a, 0x53,
	0x06, 0xe4, 0x48, 0x65, 0x41, 0x08, 0x31, 0xb4, 0x02, 0xb1, 0xd0, 0x21, 0x54, 0x1d, 0x58, 0x22,
	0x17, 0xdc, 0x34, 0x22, 0x89, 0xa3, 0xd8, 0x09, 0x74, 0xe3, 0x1f, 0xd0, 0x7f, 0xc4, 0xda, 0xb1,
	0x23, 0x13, 0xa0, 0xf6, 0x8f, 0x20, 0xdb, 0xfd, 0xa0, 0x48, 0x05, 0xe9, 0x6d, 0xbe, 0xd7, 0xe7,
	0xdc, 0x73, 0xcf, 0xd1, 0x85, 0x41, 0x47, 0xb9, 0x20, 0xb1, 0xf8, 0x94, 0x57, 0xb1, 0x68, 0x48,
	0x5e, 0xe5, 0x55, 0x96, 0x72, 0x41, 0x04, 0xc5, 0x75, 0xc3, 0x04, 0x43, 0x50, 0x01, 0xb0, 0x04,
	0xb8, 0x37, 0x19, 0xcb, 0x98, 0x6a, 0xc7, 0xf2, 0xa5, 0x11, 0x6e, 0x90, 0x31, 0x96, 0x15, 0x34,
	0x56, 0xd5, 0xb4, 0x9d, 0xc5, 0x22, 0x2f, 0x25, 0xa7, 0xac, 0x35, 0xe0, 0xf6, 0xab, 0x09, 0x1f,
	0x8c, 0x77, 0xb3, 0xdf, 0xca, 0xd1, 0xe8, 0x06, 0x5e, 0x74, 0xa4, 0x68, 0xa9, 0x03, 0x42, 0x10,
	0xf5, 0x12, 0x5d, 0x20, 0x0f, 0xda, 0x52, 0x26, 0xad, 0x48, 0x49, 0x1d, 0x33, 0x04, 0x91, 0x9d,
	0xf4, 0x64, 0x63, 0x44, 0x4a, 0x8a, 0x86, 0x10, 0x72, 0x41, 0x1a, 0x91, 0xca, 0xe9, 0x8e, 0x15,
	0x82, 0xe8, 0xb2, 0xef, 0x62, 0x2d, 0x8d, 0xf7, 0xd2, 0x78, 0xbc, 0x97, 0x1e, 0xf4, 0x56, 0x3f,
	0x02, 0x63, 0xf9, 0x33, 0x00, 0x89, 0xad, 0x78, 0xf2, 0x07, 0xbd, 0x80, 0xde, 0xc1, 0xe4, 0x7b,
	0x56, 0xcd, 0xf2, 0xac, 0x6d, 0x88, 0xc8, 0x59, 0x95, 0xce, 0x09, 0x9f, 0x3b, 0xf7, 0x94, 0xe6,
	0xc3, 0x3d, 0x64, 0xf8, 0x27, 0xe2, 0x35, 0xe1, 0x73, 0xf4, 0x0a, 0x5e, 0x77, 0xa4, 0xc8, 0x3f,
	0x68, 0x8e, 0x8a, 0xc9, 0xb9, 0x50, 0xab, 0x78, 0xf8, 0x98, 0x13, 0x9e, 0x1c, 0x30, 0xca, 0x6e,
	0x72, 0xd5, 0x9d, 0x36, 0x6e, 0xbf, 0x99, 0xf0, 0xea, 0x2f, 0xd0, 0x99, 0x4c, 0x4e, 0x6d, 0x9b,
	0x77, 0xb3, 0xfd, 0x05, 0xc0, 0x47, 0x25, 0xa9, 0xd3, 0xdd, 0x1a, 0xac, 0xe1, 0xe9, 0x94, 0x72,
	0xd1, 0x50, 0xde, 0x16, 0x42, 0x39, 0xb7, 0x42, 0x2b, 0xba, 0xec, 0x3f, 0xff, 0x87, 0x09, 0xfc,
	0x86, 0xd4, 0x93, 0x03, 0x7f, 0x70, 0x42, 0x7f, 0x59, 0x89, 0x66, 0x91, 0x78, 0xe5, 0x79, 0x84,
	0x3b, 0x82, 0xe1, 0xff, 0x06, 0xa0, 0x6b, 0x68, 0x7d, 0xa4, 0x0b, 0xe5, 0xdf, 0x4e, 0xe4, 0xf3,
	0x98, 0x89, 0xbe, 0x06, 0x5d, 0x3c, 0x33, 0x9f, 0x82, 0xc1, 0xe3, 0xd5, 0xc6, 0x07, 0xeb, 0x8d,
	0x0f, 0x7e, 0x6d, 0x7c, 0xb0, 0xdc, 0xfa, 0xc6, 0x7a, 0xeb, 0x1b, 0xdf, 0xb7, 0xbe, 0xf1, 0x0e,
	0xe9, 0x8b, 0xfe, 0xbc, 0xbb, 0xe9, 0x45, 0x4d, 0xf9, 0xf4, 0xbe, 0x4a, 0xea, 0xc9, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0xef, 0xf5, 0xe7, 0xee, 0x02, 0x00, 0x00,
}

func (m *TrainingState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainingState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainingState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidationState != nil {
		{
			size, err := m.ValidationState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTrainingState(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TrainingConfigurationHash) > 0 {
		i -= len(m.TrainingConfigurationHash)
		copy(dAtA[i:], m.TrainingConfigurationHash)
		i = encodeVarintTrainingState(dAtA, i, uint64(len(m.TrainingConfigurationHash)))
		i--
		dAtA[i] = 0x22
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintTrainingState(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x1a
	if len(m.TwinName) > 0 {
		i -= len(m.TwinName)
		copy(dAtA[i:], m.TwinName)
		i = encodeVarintTrainingState(dAtA, i, uint64(len(m.TwinName)))
		i--
		dAtA[i] = 0x12
	}
	if m.Value {
		i--
		if m.Value {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ValidationState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidationState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidationState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MapValidatorsBestresulthash) > 0 {
		for k := range m.MapValidatorsBestresulthash {
			v := m.MapValidatorsBestresulthash[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintTrainingState(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintTrainingState(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintTrainingState(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1a
		}
	}
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintTrainingState(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	if m.Value {
		i--
		if m.Value {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTrainingState(dAtA []byte, offset int, v uint64) int {
	offset -= sovTrainingState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TrainingState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value {
		n += 2
	}
	l = len(m.TwinName)
	if l > 0 {
		n += 1 + l + sovTrainingState(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovTrainingState(uint64(l))
	l = len(m.TrainingConfigurationHash)
	if l > 0 {
		n += 1 + l + sovTrainingState(uint64(l))
	}
	if m.ValidationState != nil {
		l = m.ValidationState.Size()
		n += 1 + l + sovTrainingState(uint64(l))
	}
	return n
}

func (m *ValidationState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value {
		n += 2
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovTrainingState(uint64(l))
	if len(m.MapValidatorsBestresulthash) > 0 {
		for k, v := range m.MapValidatorsBestresulthash {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTrainingState(uint64(len(k))) + 1 + len(v) + sovTrainingState(uint64(len(v)))
			n += mapEntrySize + 1 + sovTrainingState(uint64(mapEntrySize))
		}
	}
	return n
}

func sovTrainingState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTrainingState(x uint64) (n int) {
	return sovTrainingState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TrainingState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainingState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainingState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Value = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwinName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwinName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrainingConfigurationHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrainingState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrainingConfigurationHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidationState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ValidationState == nil {
				m.ValidationState = &ValidationState{}
			}
			if err := m.ValidationState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidationState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidationState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidationState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Value = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MapValidatorsBestresulthash", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrainingState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrainingState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MapValidatorsBestresulthash == nil {
				m.MapValidatorsBestresulthash = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTrainingState
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTrainingState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTrainingState
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthTrainingState
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTrainingState
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthTrainingState
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthTrainingState
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTrainingState(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthTrainingState
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.MapValidatorsBestresulthash[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTrainingState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTrainingState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTrainingState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTrainingState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTrainingState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTrainingState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTrainingState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTrainingState = fmt.Errorf("proto: unexpected end of group")
)
