// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesta/twin/training_state.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TrainingState struct {
	TrainingState bool `protobuf:"varint,1,opt,name=training_state,json=trainingState,proto3" json:"training_state,omitempty"`
}

func (m *TrainingState) Reset()         { *m = TrainingState{} }
func (m *TrainingState) String() string { return proto.CompactTextString(m) }
func (*TrainingState) ProtoMessage()    {}
func (*TrainingState) Descriptor() ([]byte, []int) {
	return fileDescriptor_672fc39fef593be7, []int{0}
}
func (m *TrainingState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrainingState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrainingState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrainingState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainingState.Merge(m, src)
}
func (m *TrainingState) XXX_Size() int {
	return m.Size()
}
func (m *TrainingState) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainingState.DiscardUnknown(m)
}

var xxx_messageInfo_TrainingState proto.InternalMessageInfo

func (m *TrainingState) GetTrainingState() bool {
	if m != nil {
		return m.TrainingState
	}
	return false
}

func init() {
	proto.RegisterType((*TrainingState)(nil), "vesta.twin.TrainingState")
}

func init() { proto.RegisterFile("vesta/twin/training_state.proto", fileDescriptor_672fc39fef593be7) }

var fileDescriptor_672fc39fef593be7 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x4b, 0x2d, 0x2e,
	0x49, 0xd4, 0x2f, 0x29, 0xcf, 0xcc, 0xd3, 0x2f, 0x29, 0x4a, 0xcc, 0xcc, 0xcb, 0xcc, 0x4b, 0x8f,
	0x2f, 0x2e, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x2b, 0xd0,
	0x03, 0x29, 0x50, 0x32, 0xe3, 0xe2, 0x0d, 0x81, 0xaa, 0x09, 0x06, 0x29, 0x11, 0x52, 0xe5, 0xe2,
	0x43, 0xd5, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x11, 0xc4, 0x5b, 0x82, 0xac, 0xcc, 0x49, 0xe7,
	0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e,
	0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x84, 0x20, 0xd6, 0x57, 0x40, 0x1d,
	0x50, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0xb6, 0xd8, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0a,
	0xed, 0x15, 0xc4, 0x9b, 0x00, 0x00, 0x00,
}

func (m *TrainingState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrainingState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrainingState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TrainingState {
		i--
		if m.TrainingState {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTrainingState(dAtA []byte, offset int, v uint64) int {
	offset -= sovTrainingState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TrainingState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrainingState {
		n += 2
	}
	return n
}

func sovTrainingState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTrainingState(x uint64) (n int) {
	return sovTrainingState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TrainingState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrainingState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrainingState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrainingState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrainingState", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TrainingState = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTrainingState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTrainingState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTrainingState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTrainingState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrainingState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTrainingState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTrainingState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTrainingState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTrainingState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTrainingState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTrainingState = fmt.Errorf("proto: unexpected end of group")
)
